import sys, os ; sys.path.append(os.path.join(os.path.dirname(__file__),"../../"))
from Common.Library.CustomException import CustomException
class GetLanguageCode:
    def language_code(self, language):
        language_dict = {'Afrikaans':'afr',
                        'Arabic':'ara',
                        'Bulgarian':'bul',
                        'Bengali':'ben',
                        'Catalan':'cat',
                        'Czech':'ces',
                        'Welsh':'cym',
                        'Danish':'dan',
                        'German':'deu',
                        'Greek':'ell',
                        'English':'eng',
                        'Spanish':'spa',
                        'Estonian':'est',
                        'Persian':'fas',
                        'Finnish':'fin',
                        'French':'frm',
                        'Gujarati':'guj',
                        'Hebrew':'heb',
                        'Hindi':'hin',
                        'Croatian':'hrv',
                        'Hungarian':'hun',
                        'Indonesian':'ind',
                        'Italian':'ita',
                        'Japanese':'jpn',
                        'Kannada':'kan',
                        'Korean':'kor',
                        'Lithuanian':'lit',
                        'Latvian':'lav',
                        'Macedonian':'mkd',
                        'Malayalam':'mal',
                        'Marathi':'mar',
                        'Nepali':'nep',
                        'Dutch':'nld',
                        'Norwegian':'nor',
                        'Panjabi':'pan',
                        'Polish':'pol',
                        'Portuguese':'por',
                        'Romanian':'ron',
                        'Russian':'rus',
                        'Slovak':'slk',
                        'Slovenian':'slv',
                        'Albanian':'sqi',
                        'Swedish':'swe',
                        'Swahili':'swa',
                        'Tamil':'tam',
                        'Telugu':'tel',
                        'Thai':'tha',
                        'Tagalog':'tgl',
                        'Turkish':'tur',
                        'Ukrainian':'ukr',
                        'Urdu':'urd',
                        'Vietnamese':'vie',
                        'Chinese Traditional':'chi_tra',
                        'Chinese Simplified':'chi_sim'}
        try:
            language = language.title()
            code = language_dict[language]
        except KeyError:
            raise CustomException("Language code not found")
        return code
    
    def language_code_easyocr(self, languages):
        language_dict = {"Abaza":"abq",
                        "Adyghe":"ady",
                        "Afrikaans":"af",
                        "Angika":"ang",
                        "Arabic":"ar",
                        "Assamese":"as",
                        "Avar":"ava",
                        "Azerbaijani":"az",
                        "Belarusian":"be",
                        "Bulgarian":"bg",
                        "Bihari":"bh",
                        "Bhojpuri":"bho",
                        "Bengali":"bn",
                        "Bosnian":"bs",
                        "Simplified Chinese":"ch_sim",
                        "Traditional Chinese":"ch_tra",
                        "Chechen":"che",
                        "Czech":"cs",
                        "Welsh":"cy",
                        "Danish":"da",
                        "Dargwa":"dar",
                        "German":"de",
                        "English":"en",
                        "Persian(Farsi)":"fa",
                        "French":"fr",
                        "Irish":"ga",
                        "Goan Konkani":"gom",
                        "Hindi":"hi",
                        "Croatian":"hr",
                        "Hungarian":"hu",
                        "Indonesian":"id",
                        "Ingush":"inh",
                        "Icelandic":"is",
                        "Italian":"it",
                        "Japanese":"ja",
                        "Kabardian":"kbd",
                        "Kannada":"kn",
                        "Korean":"ko",
                        "Kurdish":"ku",
                        "Latin":"la",
                        "Lak":"lbe",
                        "Lezghian":"lez",
                        "Lithuanian":"lt",
                        "Latvian":"lv",
                        "Magahi":"mah",
                        "Maithili":"mai",
                        "Maori":"mi",
                        "Mongolian":"mn",
                        "Marathi":"mr",
                        "Malay":"ms",
                        "Maltese":"mt",
                        "Nepali":"ne",
                        "Newari":"new",
                        "Dutch":"nl",
                        "Norwegian":"no",
                        "Occitan":"oc",
                        "Pali":"pi",
                        "Polish":"pl",
                        "Portuguese":"pt",
                        "Romanian":"ro",
                        "Russian":"ru",
                        "Serbian(cyrillic)":"rs_cyrillic",
                        "Serbian(latin)":"rs_latin",
                        "Nagpuri":"sck",
                        "Slovak":"sk",
                        "Slovenian":"sl",
                        "Albanian":"sq",
                        "Swedish":"sv",
                        "Swahili":"sw",
                        "Tamil":"ta",
                        "Tabassaran":"tab",
                        "Telugu":"te",
                        "Thai":"th",
                        "Tajik":"tjk",
                        "Tagalog":"tl",
                        "Turkish":"tr",
                        "Uyghur":"ug",
                        "Ukranian":"uk",
                        "Urdu":"ur",
                        "Uzbek":"uz",
                        "Vietnamese":"vi"}
        try:
            codes=[]
            for each in languages:
                each = each.title()
                codes.append(language_dict[each])
        except KeyError:
            raise CustomException("Language code not found")
        return codes